//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fit2Work.Services.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Fit2Work.Services.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///client1,Fname1,Lname1,447999999991
        ///client1,Fname2,Lname2,447999999991.
        /// </summary>
        public static string Users_Duplicates {
            get {
                return ResourceManager.GetString("Users_Duplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///client1,Fname1,Lname1,+447999009001
        ///client1,Fname2,Lname2,00447999009002
        ///client1,Fname3,Lname3,7999009003
        ///client1,Fname4,Lname4,0799009004
        ///client1,Fname5,Lname5,+447999009005
        ///client1,Fname6,Lname6,00447999009006
        ///client1,Fname7,Lname7,07999009007
        ///client1,Fname8,Lname8,7999009008
        ///client1,Fname9,Lname9,+447999009009
        ///client1,Fname10,Lname10,00447999009010
        ///.
        /// </summary>
        public static string Users_Invalid_WithValidMemberCode {
            get {
                return ResourceManager.GetString("Users_Invalid_WithValidMemberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///client1,Fname1,Lname1,447999009001
        ///client1,Fname2,Lname2,447999009002
        ///client1,Fname3,Lname3,+447999009003
        ///client1,Fname4,Lname4,00447999009004
        ///client1,Fname5,Lname5,07999009005
        ///client1,Fname6,Lname6,7999009006
        ///client1,Fname7,Lname7,447999009007
        ///client1,Fname8,Lname8,447999009008
        ///client1,Fname9,Lname9,+447999009009
        ///client1,Fname10,Lname10,00447999009010
        ///.
        /// </summary>
        public static string Users_Mixed_WithValidMemberCode {
            get {
                return ResourceManager.GetString("Users_Mixed_WithValidMemberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///x,Fname1,Lname1,+447999009001
        ///x,Fname2,Lname2,00447999009002
        ///x,Fname3,Lname3,7999009003
        ///x,Fname4,Lname4,0799009004
        ///x,Fname5,Lname5,+447999009005
        ///x,Fname6,Lname6,00447999009006
        ///x,Fname7,Lname7,07999009007
        ///x,Fname8,Lname8,7999009008
        ///x,Fname9,Lname9,+447999009009
        ///x,Fname10,Lname10,00447999009010
        ///.
        /// </summary>
        public static string Users_NoCsv {
            get {
                return ResourceManager.GetString("Users_NoCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///client1,Fname1,Lname1,447999999991
        ///client1,Fname2,NewLastName,447999999991.
        /// </summary>
        public static string Users_UpdateUser {
            get {
                return ResourceManager.GetString("Users_UpdateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///client1,Fname1,Lname1,447999999991
        ///client1,Fname2,Lname2,447999999992
        ///client1,Fname3,Lname3,447999999993
        ///client1,Fname4,Lname4,447999999994
        ///client1,Fname5,Lname5,447999999995
        ///client1,Fname6,Lname6,447999999996
        ///client1,Fname7,Lname7,447999999997
        ///client1,Fname8,Lname8,447999999998
        ///client1,Fname9,Lname9,447999999999
        ///client1,Fname10,Lname10,447999999910.
        /// </summary>
        public static string Users_Valid_WithValidMemberCode {
            get {
                return ResourceManager.GetString("Users_Valid_WithValidMemberCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MemberCode,FirstName,LastName,PhoneNumber
        ///x,Fname1,Lname1,+447999009001
        ///x,Fname2,Lname2,00447999009002
        ///x,Fname3,Lname3,7999009003
        ///x,Fname4,Lname4,0799009004
        ///x,Fname5,Lname5,+447999009005
        ///x,Fname6,Lname6,00447999009006
        ///x,Fname7,Lname7,07999009007
        ///x,Fname8,Lname8,7999009008
        ///x,Fname9,Lname9,+447999009009
        ///x,Fname10,Lname10,00447999009010
        ///.
        /// </summary>
        public static string Users_WithInvalidMemberCode {
            get {
                return ResourceManager.GetString("Users_WithInvalidMemberCode", resourceCulture);
            }
        }
    }
}
